# Generated by Django 3.0.1 on 2020-01-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(max_length=30)),
                ('stamp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('namex', models.CharField(blank=True, default='', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pricex', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('gid', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('tid', models.IntegerField(default=0)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderdetails', to='orders.Product')),
            ],
        ),
    ]
