# Generated by Django 3.0.1 on 2020-01-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetail_orderheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderdetails', to='orders.OrderHeader'),
        ),
    ]
