# Generated by Django 3.0.1 on 2020-01-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djuser', models.CharField(default='new', max_length=50)),
            ],
        ),
    ]
