# Generated by Django 3.0.1 on 2020-01-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('stamp', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='member',
            name='djemail',
            field=models.EmailField(default='me@mysite.com', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='latest_suggestion',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='member',
            name='social1',
            field=models.URLField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='member',
            name='social2',
            field=models.URLField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='member',
            name='stamp_added',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='stamp_suspended',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted'), (4, 'Suspended')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='djuser',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('url', models.URLField(blank=True, default='', max_length=240)),
                ('stamp', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_suggestions', to='members.Member')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theme_suggestions', to='members.Theme')),
            ],
        ),
    ]
