# Generated by Django 3.0.1 on 2020-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200110_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='stamp_added',
        ),
        migrations.RemoveField(
            model_name='member',
            name='stamp_suspended',
        ),
        migrations.AddField(
            model_name='member',
            name='stamp',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='djemail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=1),
        ),
    ]
