# Generated by Django 3.0.1 on 2020-01-11 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200111_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StaffHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=50)),
                ('action', models.IntegerField(choices=[(1, 'Log In'), (2, 'Change Password'), (3, 'Edit Profile'), (4, 'Report Profile'), (11, 'Add Theme'), (12, 'Delete Theme'), (21, 'Add Suggestion'), (22, 'Delete Suggestion'), (23, 'Report Suggestion'), (31, 'Add Comment'), (32, 'Delete Comment'), (33, 'Report Comment'), (41, 'Add Message'), (42, 'Delete Message'), (43, 'Block Sender')], default=1)),
                ('stamp', models.CharField(max_length=30)),
                ('motivation', models.CharField(max_length=240)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='member',
            name='latest_suggestion',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='published',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='member_suggestions', to='members.Member'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.IntegerField(choices=[(1, 'Log In'), (2, 'Change Password'), (3, 'Edit Profile'), (4, 'Report Profile'), (11, 'Add Theme'), (12, 'Delete Theme'), (21, 'Add Suggestion'), (22, 'Delete Suggestion'), (23, 'Report Suggestion'), (31, 'Add Comment'), (32, 'Delete Comment'), (33, 'Report Comment'), (41, 'Add Message'), (42, 'Delete Message'), (43, 'Block Sender')], default=1),
        ),
        migrations.AlterField(
            model_name='history',
            name='stamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='member',
            name='stamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='stamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='author',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='stamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='theme',
            name='stamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='theme',
            name='status',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Archived')], default=1),
        ),
        migrations.AddIndex(
            model_name='staffhistory',
            index=models.Index(fields=['staff'], name='members_sta_staff_3940c8_idx'),
        ),
        migrations.AddField(
            model_name='blockedsender',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocking_member', to='members.Member'),
        ),
        migrations.AddField(
            model_name='blockedsender',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocked_member', to='members.Member'),
        ),
        migrations.AddIndex(
            model_name='blockedsender',
            index=models.Index(fields=['sender'], name='members_blo_sender__8f971b_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedsender',
            index=models.Index(fields=['recipient'], name='members_blo_recipie_f25639_idx'),
        ),
    ]
