# Generated by Django 3.0.1 on 2020-01-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200111_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='member_themes', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.IntegerField(choices=[(1, 'Log In'), (2, 'Change Password'), (3, 'Edit Profile'), (4, 'Report Profile'), (11, 'Add Theme'), (12, 'Delete Theme'), (21, 'Add Suggestion'), (22, 'Delete Suggestion'), (23, 'Report Suggestion'), (31, 'Add Comment'), (32, 'Delete Comment'), (33, 'Report Comment'), (41, 'Add Message'), (42, 'Delete Message'), (43, 'Block Sender'), (51, 'Add Platfrom'), (52, 'Delete Platform')], default=1),
        ),
        migrations.AlterField(
            model_name='staffhistory',
            name='action',
            field=models.IntegerField(choices=[(1, 'Log In'), (2, 'Change Password'), (3, 'Edit Profile'), (4, 'Report Profile'), (11, 'Add Theme'), (12, 'Delete Theme'), (21, 'Add Suggestion'), (22, 'Delete Suggestion'), (23, 'Report Suggestion'), (31, 'Add Comment'), (32, 'Delete Comment'), (33, 'Report Comment'), (41, 'Add Message'), (42, 'Delete Message'), (43, 'Block Sender'), (51, 'Add Platfrom'), (52, 'Delete Platform')], default=1),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('url', models.URLField(default='', max_length=80)),
                ('stamp', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Archived')], default=1)),
                ('sender', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='member_platforms', to='members.Member')),
            ],
        ),
    ]
