# Generated by Django 3.0.1 on 2020-01-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200113_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=480)),
                ('stamp', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'Initiated'), (2, 'Approved'), (3, 'Archived')], default=1)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_contacts', to='members.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='platform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='sender',
        ),
        migrations.AddField(
            model_name='history',
            name='itemid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffhistory',
            name='itemid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.IntegerField(choices=[(1, 'Log In'), (2, 'Change Password'), (3, 'Edit Profile'), (4, 'Report Profile'), (11, 'Add Theme'), (12, 'Delete Theme'), (21, 'Add Suggestion'), (22, 'Delete Suggestion'), (23, 'Report Suggestion'), (31, 'Add Comment'), (32, 'Delete Comment'), (33, 'Report Comment'), (41, 'Add Message'), (42, 'Delete Message'), (43, 'Report Sender'), (51, 'Add Platfrom'), (52, 'Delete Platform')], default=1),
        ),
        migrations.AlterField(
            model_name='platform',
            name='url',
            field=models.URLField(db_index=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='staffhistory',
            name='action',
            field=models.IntegerField(choices=[(1, 'Log In'), (2, 'Archive Profile'), (3, 'Unarchive Profile'), (11, 'Approve Theme'), (12, 'Archive Theme'), (21, 'Approve Suggestion Report'), (22, 'Archive Suggestion Report'), (31, 'Approve Comment Report'), (32, 'Archive Comment Report'), (41, 'Approve Message Report'), (42, 'Archive Message Report'), (51, 'Approve Platform'), (52, 'Archive Platform')], default=1),
        ),
        migrations.DeleteModel(
            name='BlockedSender',
        ),
    ]
