# Generated by Django 3.0.1 on 2020-01-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200115_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField(db_index=True, default=0)),
                ('itemtype', models.IntegerField(choices=[(1, 'Suggestion'), (2, 'Comment'), (3, 'Message')], default=1)),
                ('text', models.CharField(max_length=240)),
                ('stamp', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'Initiated'), (2, 'Processed'), (3, 'Archived')], default=1)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_flags', to='members.Member')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
