# Generated by Django 3.0.1 on 2020-01-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20200120_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Hidden'), (3, 'Archived')], default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Hidden'), (3, 'Archived')], default=1),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Hidden'), (3, 'Archived')], default=1),
        ),
    ]
