# Generated by Django 3.0.1 on 2020-01-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20200121_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, default='', max_length=80)),
                ('stamp', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Archived')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='platform',
            name='type',
        ),
    ]
