# Generated by Django 3.0.1 on 2020-01-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20200123_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='itemtype',
            field=models.IntegerField(choices=[(1, 'Suggestion'), (2, 'Comment'), (3, 'Message'), (4, 'Profile'), (5, 'Report')], default=1),
        ),
    ]
